# config/optimizer.yaml
# 用于策略参数调优，如网格搜索或贝叶斯优化

strategy_name: bollinger_band
optimize_params:
  period: [10, 20, 30, 40]
  devfactor: [1.5, 2.0, 2.5, 3.0]
  stop_loss: [0.03, 0.05, 0.07]
  take_profit: [0.08, 0.10, 0.12]
method: grid_search       # 可选：grid_search / bayes
