# config/strategy.yaml
# 策略参数配置，主要用于技术指标驱动类策略

strategy_name: bollinger_band

parameters:
  period: 20
  devfactor: 2.0
  stop_loss: 0.05
  take_profit: 0.1

risk_parameters:           # ✅ 添加这个字段
  max_drawdown: 0.2
  max_position: 0.3
